version: '3.1'

networks:
  default:
    external:
      name: private_bridge

services:
  kafka-manager-web:
    image: whale.mosfarm.eu/kafka-manager:1.3.3.8
    container_name: kafka-manager-web
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zookeeper:2181
